# Generated by Django 3.1.7 on 2021-05-02 13:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestenf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=30)),
                ('prixactivite', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('dateactivite', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='anneescolaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_deb', models.DateField(blank=True)),
                ('date_fin', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='charge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=30)),
                ('montant', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('pycejointe', models.FileField(blank=True, upload_to='')),
                ('datepaycharge', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='classe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default='', max_length=60)),
                ('anneescolaire', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestenf.anneescolaire')),
            ],
        ),
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default='', max_length=50)),
                ('obligatoire', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='documentmaitraisse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=30)),
                ('pycejointe', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='enfant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, default='', max_length=60)),
                ('prenom', models.CharField(blank=True, default='', max_length=60)),
                ('datenessance', models.DateField(blank=True, default=datetime.date.today)),
                ('etatmedical', models.CharField(blank=True, default='', max_length=50)),
                ('Nompere', models.CharField(blank=True, default='', max_length=30)),
                ('Nommere', models.CharField(blank=True, default='', max_length=30)),
                ('adresse', models.TextField(blank=True, default='', max_length=70)),
                ('profissionpere', models.CharField(blank=True, default='', max_length=50)),
                ('proffisionmere', models.CharField(blank=True, default='', max_length=50)),
                ('telpere', models.CharField(blank=True, default='', max_length=8)),
                ('telmere', models.CharField(blank=True, default='', max_length=8)),
                ('dateinscrit', models.DateField(blank=True, default=datetime.date.today)),
                ('classe', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestenf.classe')),
            ],
        ),
        migrations.CreateModel(
            name='frais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typefrais', models.CharField(blank=True, default='', max_length=60)),
                ('montant', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='maitresse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, default='', max_length=60)),
                ('prenom', models.CharField(blank=True, default='', max_length=60)),
                ('datenessance', models.DateField(blank=True)),
                ('villenessance', models.CharField(blank=True, default='', max_length=60)),
                ('nationalite', models.CharField(blank=True, default='', max_length=60)),
                ('cin', models.CharField(blank=True, default='', max_length=8)),
                ('datecin', models.DateField(blank=True)),
                ('nvscolaire', models.CharField(blank=True, default='', max_length=60)),
                ('specialite', models.CharField(blank=True, default='', max_length=20)),
                ('tel', models.CharField(blank=True, default='', max_length=8)),
                ('adresse', models.TextField(blank=True, default='', max_length=70)),
                ('dateemb', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='niveau',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=30)),
                ('capacitedeclass', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='regimehoraire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typeregime', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='reglementm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montantreglemaiment', models.FloatField(blank=True)),
                ('datereglemaiment', models.DateField(blank=True, default=datetime.date.today)),
                ('moisreglemaiment', models.CharField(blank=True, max_length=50)),
                ('maitresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestenf.maitresse')),
            ],
        ),
        migrations.CreateModel(
            name='reglement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montantreglemaiment', models.FloatField(blank=True)),
                ('datereglemaiment', models.DateField(blank=True, default=datetime.date.today)),
                ('moisreglemaiment', models.CharField(blank=True, max_length=50)),
                ('enfant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestenf.enfant')),
                ('frais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestenf.frais')),
            ],
        ),
        migrations.AddField(
            model_name='frais',
            name='regimehoraire',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestenf.regimehoraire'),
        ),
        migrations.AddField(
            model_name='enfant',
            name='regimehoraire',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestenf.regimehoraire'),
        ),
        migrations.CreateModel(
            name='clubenf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestenf.club')),
                ('enfant', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestenf.enfant')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='maitresse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestenf.maitresse'),
        ),
        migrations.AddField(
            model_name='classe',
            name='maitresse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestenf.maitresse'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestenf.niveau'),
        ),
        migrations.CreateModel(
            name='abcence_maitresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateabcence', models.DateField()),
                ('cause', models.CharField(blank=True, max_length=30)),
                ('maitresse', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestenf.maitresse')),
            ],
        ),
        migrations.CreateModel(
            name='abcence_enfant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateabcence', models.DateField()),
                ('cause', models.CharField(blank=True, max_length=30)),
                ('enfant', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestenf.enfant')),
            ],
        ),
    ]
