# Generated by Django 3.1.7 on 2021-05-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestenf', '0002_auto_20210502_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='cinparent',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
