# Generated by Django 3.1.7 on 2021-05-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestenf', '0004_auto_20210502_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_deactive',
            field=models.BooleanField(default=False),
        ),
    ]
