# Generated by Django 3.1.7 on 2021-05-03 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestenf', '0005_account_is_deactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
