# Generated by Django 3.1.7 on 2021-05-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestenf', '0007_auto_20210503_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcence_enfant',
            name='absant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abcence_maitresse',
            name='absant',
            field=models.BooleanField(default=False),
        ),
    ]
