# Generated by Django 3.0.5 on 2021-05-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestenf', '0008_auto_20210503_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='prix',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
