# Generated by Django 3.0.5 on 2021-05-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestenf', '0009_club_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='userpasswod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=60)),
                ('password', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
    ]
