# Generated by Django 3.0.5 on 2021-05-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestenf', '0010_userpasswod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_deactive',
        ),
    ]
