# Generated by Django 3.0.5 on 2021-05-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestenf', '0011_remove_account_is_deactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='telmere',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
