# Generated by Django 3.0.5 on 2021-05-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestenf', '0012_auto_20210515_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='cinparent',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='telmere',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
