# Generated by Django 3.0.5 on 2021-05-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestenf', '0013_auto_20210515_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abcence_enfant',
            name='absant',
        ),
    ]
