# Generated by Django 3.0.5 on 2021-05-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestenf', '0014_remove_abcence_enfant_absant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abcence_maitresse',
            name='absant',
        ),
    ]
