# Generated by Django 3.0.5 on 2021-06-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestenf', '0015_remove_abcence_maitresse_absant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='pycejointe',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
