# Generated by Django 3.0.5 on 2021-06-22 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestenf', '0016_auto_20210622_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='datepaycharge',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
